name: Build and Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
    name: Build and test (Node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14', '16', '18']

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies and test
        run: npm cit
