name: Publish npm package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a # tag=v3.4.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm i -g npm@latest
      - run: npm cit
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
