name: Publish npm package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm i -g npm@latest
      - run: npm cit
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
